### ISSUE TITLE
Torch build error

### ISSUE THREAD

**Issue by arvin1408** [hackingthemarkets/tradekit#2]
On MacOS Big Sur

Collecting torch
  Downloading torch-1.7.1-cp38-cp38-manylinux1_x86_64.whl (776.8 MB)
Killed
ERROR: Service 'web' failed to build : The command '/bin/sh -c pip3 install -r requirements.txt' returned a non-zero code: 137

**Comment by tywangcharlie** [comment]
I got the same error message.
After searching for "docker returned a non-zero code: 137", [ERROR: Build process returned exit code 137 during Docker build on Tutum](https://stackoverflow.com/questions/34674325/error-build-process-returned-exit-code-137-during-docker-build-on-tutum), it might be caused by docker out of the memory.

Simply scaling up the memory allocation setting in Docker > Preference > Memory fixes the problem.

**Comment by gmacie** [comment]
Also maybe python 3.8. I had the same error and found that Big Sur needs 3.9
Sorry, busy with work. I will try to add the reference to this later. I had also seen the memory fix but haven't tried either possible solution.

**Comment by arvin1408** [comment]
> I got the same error message.
> After searching for "docker returned a non-zero code: 137", [ERROR: Build process returned exit code 137 during Docker build on Tutum](https://stackoverflow.com/questions/34674325/error-build-process-returned-exit-code-137-during-docker-build-on-tutum), it might be caused by docker out of the memory.
> 
> Simply scaling up the memory allocation setting in Docker > Preference > Memory fixes the problem.

Increased Docker memory to 5.0GB and build was successful. Thanks!
